name: RELEASE LIB
on:
    push:
        branches: master
    workflow_dispatch:
permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

            - uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: Setup git
              run: |
                  git config --local user.email "4944278+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"

            - run: npm version patch --no-git-tag-version

            - uses: Klemensas/action-autotag@stable
              with:
                  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
                  tag_prefix: 'v'

            - name: Zip
              uses: TheDoctor0/zip-release@0.6.1
              with:
                  filename: ias-lua-lib.zip
                  path: ./ias-lib

            - name: Artifact
              uses: actions/upload-artifact@v2.3.1
              with:
                  name: ias-lua-lib
                  path: ./ias-lua-lib.zip

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: ias-lua-lib.zip

            - name: Commit files
              run: |
                  git commit --allow-empty -m "Version Bump" -a
                  git push origin master
