name: CI
on:
    create:
        tags:
            - v*
    workflow_dispatch:
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Zip
              uses: TheDoctor0/zip-release@0.6.1
              with:
                  # Filename for archive
                  filename: ias-lua-lib.zip
                  # Base path for archive files
                  path: ./ias-lib

            - name: Artifact
              uses: actions/upload-artifact@v2.3.1
              with:
                  name: ias-lua-lib
                  path: ./ias-lua-lib.zip

            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: ias-lua-lib.zip
